## How to create numpy 1-D Array ?

In [1]:
import numpy as np
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)
type(array1)

[1 2 3 4 5]


numpy.ndarray

In [2]:
print(array1.ndim)

1


In [3]:
import numpy as np
list1 = [1,2.0,3,4,5]
array1 = np.array(list1)
print(array1)
type(array1)

[1. 2. 3. 4. 5.]


numpy.ndarray

In [4]:
import numpy as np
list1 = [1,'hello',3,4,5]
array1 = np.array(list1)
print(array1)
type(array1)

['1' 'hello' '3' '4' '5']


numpy.ndarray

In [5]:
import numpy as np
list1 = [10,20,'30',40,50]
ar3 = np.array(list1)
print(ar3)

['10' '20' '30' '40' '50']


It will convert all the elements into string

Numpy array contains elements of same type - They are homogenous in nature

In [6]:
import numpy as np
list1 = [10,20,30,30,50]
ar3 = np.array(list1, dtype= str)
print(ar3)

#dtype - specifies the type of data stored in an array 

['10' '20' '30' '30' '50']


## How to create numpy 2D array ?

In [2]:
import numpy as np
l = [ [10,20,30], [40,50,60], [70,80,90] ]
a = np.array(l)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [8]:
print(a.ndim)

2


In [3]:
print(a.shape)

(3, 3)


In [ ]:
The shape of an array can be defined as the number of elements in each dimension.