## Indexing

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [3]:
print(arr[0])

10


In [4]:
print(arr[1])

20


In [5]:
import numpy as np
arr = np.array([(10,20,30), (40,50,60), (70,80,90)])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
print(arr[1,2])

60


In [8]:
print(arr[0,:])

[10 20 30]


In [9]:
print(arr[1,:])

[40 50 60]


In [10]:
print(arr[:,0])

[10 40 70]


In [11]:
print(arr[:,1])

[20 50 80]


In [12]:
print(arr[:,2])

[30 60 90]


#### https://www.programiz.com/python-programming/numpy/array-indexing
#### https://www.youtube.com/watch?v=XLOsE-xxGN0

## Slicing

Slicing is a way to extract a subset of data from a numpy array

[ start, stop, step ]

 We stop just before the stop.
 Bcz indexing starts from zero


 Start --> Start
 
 Stop --> Just before the stop
 

 By default  :
 start --> 0
 step  --> 1 step 
 

### 1-D Array

In [14]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
print(arr[1:3])

# Start -> 1
# Stop -> 3

# Here, we are stopping at index 2, just before the stop.
# Reason -> indexing starts at zero

[20 30]


In [15]:
print(arr[1:6:2])

[20 40 60]


In [17]:
print(arr[::2])

[10 30 50 70]


In [18]:
print(arr[::-1])

[70 60 50 40 30 20 10]


### 2-D Array

In [1]:
import numpy as np
arr = np.array([ [15,16,17], [25,26,27], [35,36,37], [45,46,47]])
print(arr)

[[15 16 17]
 [25 26 27]
 [35 36 37]
 [45 46 47]]


In [21]:
print(arr[1, ])

[25 26 27]


In [23]:
print(arr[:, 1])

[16 26 36 46]


In [24]:
print(arr[1:3, 1:3])

[[26 27]
 [36 37]]


In [25]:
print(arr[1:3, ])

[[25 26 27]
 [35 36 37]]


In [26]:
print(arr[:, 1:3])

[[16 17]
 [26 27]
 [36 37]
 [46 47]]


In [27]:
print(arr[1:3,1])

[26 36]


In [28]:
print(arr[1:3, :1])

[[25]
 [35]]


### https://www.youtube.com/watch?v=atG-l8VI8z4