## Numpy functions

np.ones()

np.zeros()

np.full()

np.empty()

np.arange()

np.linspace()

np.identity()

np.eye()

np.random.rand()

np.random.rand.int()

np.shape()

np.reshape()

### np.ones()

It will create arrays filled with ones

In [7]:
import numpy as np
arr = np.ones(5)
print(arr)

#Here it will create 1-D array filled with 5 ones

[1. 1. 1. 1. 1.]


In [8]:
import numpy as np
arr = np.ones(5, dtype=int)
print(arr)

#Here, we are creating 1-D array filled with 5 ones of int type

[1 1 1 1 1]


In [11]:
import numpy as np
arr = np.ones((2,3))
print(arr)

# Create 2-D array
# 2 -> Rows
# 3 -> Columns
# Datatype - By default - float

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
import numpy as np
arr = np.ones((2,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


### np.zeros()

It will create arrays filled with zeros

In [14]:
import numpy as np
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [15]:
import numpy as np
arr = np.zeros(5, dtype=int)
print(arr)

[0 0 0 0 0]


In [16]:
import numpy as np
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
import numpy as np
arr = np.zeros((2,3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


### np.full()

Full Array - An array in which all values are same (constant)

Syntax -

np.full(shape, fill_value)

shape means - 1-D, 2-D, 3-D

fill_value  - values to be filled

Default datatype -> integer

In [1]:
import numpy as np
f2 = np.full(5, 10)
print(f2)

# creates a NumPy array of length 5 where every element is filled with the value 10.

[10 10 10 10 10]


In [28]:
import numpy as np
a = np.full(3,5)
print(a)

[5 5 5]


### 2-D Array

In [30]:
import numpy as np
a = np.full((3,3),5)
print(a)

#creates a 2-D NumPy array where every element is filled with the value 5.

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [4]:
import numpy as np
a = np.full((3,3), 5, dtype=float)
print(a)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [6]:
a.shape
# To check the shape of array  
# a - name of the array

(3, 3)

In [7]:
a.size
# To check the size of array
# a - name of the array

9

In [8]:
a.ndim
# To check the dimension of array
# a - name of the array

2

### np.empty()

Empty function is used to create an array of arbitary values

Syntax

np.empy(shape, dtype)

Shape can be in list or tuple form

default datatype is float


The np.empty function in NumPy creates an array without initializing its values. 

This means that the content of the array is arbitrary and can be anything that was in memory at the time of allocation.



### 1-D Array

In [13]:
import numpy as np
a = np.empty(5)
print(a)

[ 1.    2.75  6.   10.75 17.  ]


In [14]:
import numpy as np
a = np.empty(5, dtype = int)
print(a)

[4607182418800017408 4613374868287651840 4618441417868443648
 4622241330054037504 4625478292286210048]


### 2-D Array

In [15]:
import numpy as np
a = np.empty((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
import numpy as np
a = np.empty((2,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]]


### 3-D Array

In [17]:
import numpy as np
a = np.empty([2, 5, 3])
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
In the context of the NumPy empty function, the parameters [2, 5, 3] specify the shape of the array to be created. 
Here's what each of these dimensions represents:

2 is the number of matrices (or 2D arrays) in the array.
5 is the number of rows in each matrix.
3 is the number of columns in each matrix.
Thus, the resulting array has the shape (2, 5, 3) which can be visualized as:

Two 2D arrays (or matrices),
Each 2D array has five rows,
Each row has three columns.

### np.arange()


The np.arange() function in NumPy is used to generate an array with evenly spaced values within a given interval.

Syntax -

np.arange(start,stop,step)

start & step -> optional

stop - required

If start is not specified, its default value is 0

If step is not provided, its default value is 1

In [1]:
#Create an array from 0 to 9
import numpy as np
np.arange(10)

#If only one argument is provided, it is considered as stop with start defaulting to 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# Create an array from 3 to 9
import numpy as np
arr = np.arange(1,10)
print(arr)

# creates a NumPy array containing a sequence of numbers starting from 1 up to, but not including, 10.

[1 2 3 4 5 6 7 8 9]


In [5]:
# Create an array from 1 to 9 with a step of 2
import numpy as np
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [6]:
import numpy as np
arr = np.arange(0,1,0.2)
print(arr)

[0.  0.2 0.4 0.6 0.8]


In [7]:
#Create an array from 0 to 9 with data type as float
import numpy as np
arr = np.arange(10, dtype=float)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### np.linspace()

np.linspace(start,stop,num)

start: The starting value of the sequence.

stop: The end value of the sequence.

num: The number of evenly spaced values to generate. The default is 50. 

The np.linspace() function in NumPy create evenly spaced arrays with a specified number of elements.

In [2]:
import numpy as np
arr = np.linspace(1,10,num=5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [4]:
arr = np.linspace(1,5,num=3)
print(arr)

[1. 3. 5.]


### np.eye()

np.eye(n,m,k)

n --> rows ( compulsory argument )

m --> columns 

k --> diagonal 

Returns a 2-D array , where all the diagonal elements are one & zero elsewhere

By default , 
m = n 

k = 0

In [1]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np
arr = np.eye(3,dtype=int)
print(arr)

#If we don't pass anything for m, m value will be same as n

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3]:
import numpy as np
arr = np.eye(3,5, dtype="int")
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [6]:
import numpy as np
arr = np.eye(3,5,k=1, dtype="int")
print(arr)

#If we want to customise / change the diagonal, we do it using k

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


### np.identity()


Returns the identity array

np.identity(n)

n -> It represent both no of rows & no of cols

Identity matrix :
All the diagonal elements are 1, remaining all the elements are 0.

In [ ]:
It is exactly same as eye() function, the difference here is, number of rows & no of columns must be same.
You can't customise the diagonal

In [7]:
import numpy as np
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
import numpy as np
arr = np.identity(3, dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### np.random.rand()

Generates an array of random values

Values range from 0 to 1

np.random.rand()

By default - It will give one random value

np.random.rand(n)

n - If we specify n, It will give an array of n values ranging from 0 to 1

In [10]:
import numpy as np
arr = np.random.rand(3)
print(arr)

[0.97255475 0.31070961 0.0339983 ]


### np.random.randint()

It will generate random integer value within the range a to b, where a must be less than or equal to b
( Both boundary values will be included )

In [21]:
import numpy as np
arr = np.random.randint(5,8)
print(arr)

#It will generate random integer values between 5 & 8 (Both boundary values will be included)

7


### np.shape()

It gives a tuple of array dimension

We use shape to get array dimension

### np.reshape()

It gives a new shape to an array without changing its data

It creates a new array & doesn't modify the original array itself