## Arithmetic Operation

### Addition - (+)

In [2]:
import numpy as np
x = np.array([[1,2],
               [3,4]])
y = np.array([[11,12],
              [13,14] ])
z = x + y
print(z)

[[12 14]
 [16 18]]


### Subtraction -  (-)

In [3]:
import numpy as np
x = np.array([ [1,2], 
               [3,4] ])
y = np.array([ [11,12],
               [13,14] ])
z = x - y
print(z)

[[-10 -10]
 [-10 -10]]


### Multiplication - (*)

In [4]:
import numpy as np
x = np.array([ [1,2],
               [3,4] ])
y = np.array( [ [11,12], 
                [13,14] ] )
z = x * y
print(z)

[[11 24]
 [39 56]]


### Matrix Mulitplication - ( @ )

In [5]:
import numpy as np
x = np.array([ [1,2],
               [3,4] ])
y = np.array( [ [11,12], 
                [13,14] ] )
z = x @ y
print(z)

[[37 40]
 [85 92]]


### Division - ( / )

In [7]:
import numpy as np
x = np.array([ [1,2],
               [3,4] ])
y = np.array( [ [11,12], 
                [13,14] ] )
z =  y / x
print(z)

# / -> It gives us quotient 

[[11.          6.        ]
 [ 4.33333333  3.5       ]]


### Floor Division - ( // )

In [8]:
import numpy as np
x = np.array([ [1,2],
               [3,4] ])
y = np.array( [ [11,12], 
                [13,14] ] )
z =  y // x
print(z)

# // -> It also gives us quotient, but as an integer

[[11  6]
 [ 4  3]]


### Exponentiation - ( ** )

In [9]:
import numpy as np
x = np.array([ [1,2],
               [3,4] ])
y = np.array( [ [11,12], 
                [13,14] ] )
z =  y ** x
print(z)

[[   11   144]
 [ 2197 38416]]


### Modulo - ( % )

In [10]:
import numpy as np
x = np.array([ [1,2],
               [3,4] ])
y = np.array( [ [11,12], 
                [13,14] ] )
z =  y % x
print(z)

# % -> It gives us remainder

[[0 0]
 [1 2]]


### Transpose 

In [1]:
import numpy as np
x = np.array([ [1,2],
               [3,4] ])
y = np.array( [ [11,12], 
                [13,14] ] )
print(x.transpose())
print(y.transpose())

# Transpose means :
# Rows becomes Columns
# Columns becomes Rows

[[1 3]
 [2 4]]
[[11 13]
 [12 14]]
