## Basics

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
b = np.array([ [8,7,6], [5,4,3] ])
print(b)

[[8 7 6]
 [5 4 3]]


In [15]:
# Get dimension

# ndim -> To check the dimension of an array

In [14]:
a.ndim

1

In [5]:
b.ndim

2

In [9]:
# Get Shape
# shape -> To check the shape of an array
# The shape() method returns the shape of an array i.e the number of elements in each dimension.
# The shape() method returns the shape of an array as a tuple.

In [8]:
a.shape

(5,)

In [7]:
b.shape

(2, 3)

In [10]:
# Get type

a.dtype

dtype('int64')

In [ ]:
# Get itemsize
#itemsize returns the size (in bytes) of each element of a NumPy array
# itemsize will be 8, because this array consists of integers and size of integer (in bytes) is 8 bytes.

In [12]:

a.itemsize

8

In [13]:
b.itemsize

8

## Accessing / Changing specific elements, rows, columns, etc

In [16]:
a = np.array([ [1,2,3,4,5,6,7], [8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific element [row,column]
a[1,6]

14

In [18]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
a[1, ]

array([ 8,  9, 10, 11, 12, 13, 14])

In [20]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [21]:
# Some more [startindex, endindex, stepsize ]

In [22]:
a[0, 1:5:1]

array([2, 3, 4, 5])

In [24]:
a[0, 1:-2:1]

array([2, 3, 4, 5])

In [26]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [27]:
a[:,2] = 5

In [28]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [29]:
a[:,2] = [1,2]

In [30]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3-D Array

In [31]:
b = np.array([ [[1,2],[3,4]], [[5,6],[7,8]] ])

In [32]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
# Get specific element ( work outside in )

In [35]:
b[0,1,1]

# 0 -> select 1st 2-D Matrix
# 1 -> select 2nd row of 2-D Matrix
# 1 -> select 2nd element of 2nd row

# Note -> 0,1,1 are indices

4

## Initializing different types of Arrays

In [37]:
# All 0's matrix
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [39]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [40]:
c = np.zeros((2,3,3))
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [44]:
#All 1s matrix
a = np.ones(5, dtype=int)
print(a)

[1 1 1 1 1]


In [47]:
b = np.ones((3,3), dtype=int)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [50]:
c = np.ones((4,3,3),dtype=int)
print(c)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [51]:
# Any other number
a = np.full(5,10)
print(a)

[10 10 10 10 10]


In [53]:
b = np.full((2,2), 10)
print(b)

[[10 10]
 [10 10]]


In [55]:
c = np.full((3,2,2), 10)
print(c)

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [57]:
# Random decimal numbers
a = np.random.rand(5)
print(a)

[0.32396249 0.22784802 0.44279115 0.01593372 0.98039801]


In [58]:
b = np.random.rand(3,3)
print(b)

[[0.34634088 0.40313959 0.77838725]
 [0.63694893 0.48263307 0.92161209]
 [0.74380969 0.25938122 0.17691612]]


In [60]:
c = np.random.rand(2,3,3)
print(c)

[[[0.5397172  0.79753033 0.44308283]
  [0.2220777  0.86722054 0.18027925]
  [0.79418588 0.25219413 0.54586897]]

 [[0.27686961 0.98176437 0.29146174]
  [0.22672408 0.17026945 0.28670199]
  [0.3229021  0.26658725 0.56256268]]]


In [63]:
# Random integer numbers

a = np.random.randint(7, size=(3,3))
print(a)

[[3 4 5]
 [6 3 0]
 [4 2 2]]


In [65]:
b = np.random.randint(4,7)
print(b)

5


In [66]:
# Identity matrix
# Identity matrix : All the diagonal elements are 1, remaining all the elements are 0.
# Square matrix by nature

a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [75]:
output = np.ones((5,5), dtype=int)
print(output)

z = np.zeros((3,3), dtype=int)
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Mathematics

In [76]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [77]:
a + 2

array([3, 4, 5, 6, 7])

In [79]:
a - 2

array([-1,  0,  1,  2,  3])

In [80]:
a * 2

array([ 2,  4,  6,  8, 10])

In [81]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [83]:
b = np.array([1,0,1,0,1])
a + b

array([2, 2, 4, 4, 6])

In [84]:
# https://numpy.org/doc/stable/reference/routines.math.html

## Linear Algebra

In [87]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [88]:
#https://numpy.org/doc/stable/reference/routines.linalg.html

## Statistics

In [90]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.min(stats)

1

In [92]:
np.min(stats, axis=1)

array([1, 4])

In [93]:
np.max(stats)

6

In [94]:
np.max(stats, axis=1)

array([3, 6])

## Reorganizing Arrays

In [105]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [107]:
#Vertical Stacking vectors
#vector -> 1-D array is called  vector

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
#Horizontal Stacking vectors


h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack([v1,v2])


array([1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])